application: prodigiomundial
version: 108
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: static/stylesheets
- url: /scripts
  static_dir: static/scripts
- url: /data/(.*\.json)
  mime_type: application/json
  static_files: static/data/\1
  upload: static/data/(.*\.json)
  application_readable: true
  expiration: "1h"
- url: /.*
  script: app.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
